<?php

echo "\n";
echo "<!doctype html>\n";
echo "<html lang=\"en\">\n";
echo "\n";
echo "<head>\n";
echo "    <link rel=\"shortcut icon\" href=\"hh.png\" type=\"image/x-icon\">\n";
echo "    <title>DONATE FOR THE NEED</title>\n";
echo "    <style>\n";
echo "       \n";
echo "        .head {\n";
echo "            border-radius: 10px;\n";
echo "            margin-top: 20px;\n";
echo "            margin-left: 50px;\n";
echo "            margin-right: 50px;\n";
echo "            margin-bottom: 10PX;\n";
echo "           \n";
echo "        }\n";
echo "        .footer {\n";
echo "           \n";
echo "            border-radius: 10px;\n";
echo "            height: fit-content;\n";
echo "            margin-top: 30px;\n";
echo "            padding-bottom: 10px;\n";
echo "            margin-left: 300px;\n";
echo "            margin-right: 300px;\n";
echo "        }\n";
echo "        \n";
echo "        .container{\n";
echo "            text-align: center;\n";
echo "            background-image: linear-gradient(to right, #fcf7f7, rgb(245, 239, 244));\n";
echo "            opacity: 0.7;\n";
echo "            border-radius: 10px;\n";
echo "            margin-top: 50px;\n";
echo "            margin-left: 300px;\n";
echo "            margin-right: 300px;\n";
echo "            margin-bottom: 30PX;\n";
echo "        \n";
echo "        }\n";
echo "        .center{\n";
echo "\n";
echo "             text-align: center;\n";
echo "             background-image: url('Backs1.jpg');\n";
echo "             background-repeat: no-repeat; \n";
/*echo "             background-size: cover; \n";
*/
echo "             \n";
echo "             \n";
echo "        }\n";
echo "\n";
/*echo "        .Leftbanner{\n";
echo "            position: absolute;\n";
echo "            top: 30px;\n";
echo "            right: 0;\n";
echo "            width: 200px;\n";
echo "            height: 100px";"\n";
echo "             background-size: cover; \n";
echo "          }\n";
echo "\n";
echo "        .Rightbanner{\n";
echo "            position: absolute;\n";
echo "            top: 30px;\n";
echo "            left: 0;\n";
echo "            width: 200px;\n";
echo "            height: 100px";"\n";
echo "          }\n";
echo "\n";
*/
echo "    </style>\n";
echo "</head>\n";
echo "\n";
echo "<body class=\"center\" >\n";
echo "\n";
echo "        <header class=\" head\" >\n";
echo "                <p style=\"color: black; text-align:center; padding-right:10px; font-family: Poppins; font-size:20px;\">Come forward to feed the needy amid Corona virus lockdown! </p>\n";
echo "        </header>\n";
echo "\n";
/*echo "        <div class=\"Leftbanner\">\n";
echo "                <img src=\"Leftbanner.png\"  alt=\"logo\" height=\"600\" style= \"border-radius: 4px; padding-top: 4px;\">\n";
echo "        </div>\n";
echo "        <div class=\"Rightbanner\">\n";
echo "                <img src=\"Rightbanner.png\"  alt=\"logo\" height=\"600\" style= \"border-radius: 4px; padding-top: 4px;\">\n";
echo "        </div>\n";
*/
echo "        <div class=\"container\">\n";
echo "            <h2 style=\"font-weight: bold; font-family:  Poppins; color:rgb(90, 89, 89); padding-top: 20PX;\"><br>\n";
echo "             Giving is not just about Donation <br>It is about making a difference</h2>\n";
echo "            <h3 style=\"color: rgb(253, 119, 197); font-family: Poppins; padding-bottom: 25PX;\">DONATE US</h3>\n";
echo "                <!-- Payment Button -->\n";
echo "                <form style=\"padding: 5px;\"> \n";
echo "                    <script src=\"https://checkout.razorpay.com/v1/payment-button.js\" data-payment_button_id=\"pl_HZ6xomwjttiQ6r\" async> \n";
echo "                </script>  \n";
echo "                </form>\n";
echo "                \n";
echo "            \n";
echo "        </div>\n";
echo "\n";
echo "        <!-- Footer -->\n";
echo "        <div class=\"footer\" style=\" padding: 5px; opacity: 0.7; \">\n";
echo "            <!-- Footer Links -->\n";
echo "            <div >\n";
echo "                <p style=\"font-family: Poppins; font-size:25px;\"><b>I</b> can't , But <b>we </b> can !!<br>Come Together For a Good Cause</p>\n";
echo "            \n";
echo "            </center>\n";
echo "        </div>\n";
echo "    </div>\n";
echo "\n";
echo "     <div>\n";
echo "  <img src=\"try.png\"  alt=\"logo\" height=\"200\" width=\"800\" style= \"border-radius: 4px; padding-top: 4px;\">\n";
echo "    </div>\n";
echo "            <div style=\"margin-top:60px;\">\n";
echo "                <p style=\"color: black; text-align:center; padding-right:10px; font-family: Poppins;\">© 2021 Copyright : Ranjith Devaraj  </p>\n";
echo "</body>\n";
echo "\n";
echo "</html>";

?>

